# Wicket configuration
wicket.core.settings.general.configuration-type: development
wicket.core.settings.debug.development-utilities-enabled: true
wicket.core.settings.debug.enabled: true
wicket.core.settings.debug.ajaxDebugModeEnabled: true
wicket.core.settings.debug.componentUseCheck: true